import os
import subprocess
# pylint: disable=import-error
from ai_client import FallbackClient


def get_git_diff():
    result = subprocess.run(
        ["git", "diff", "origin/main"],
        capture_output=True,
        text=True,
    )
    return result.stdout[:12000]


def parse_summary(summary: str):
    title = "AI Autonomous Changes"
    body_lines = []
    in_body = False

    for line in summary.splitlines():
        if line.startswith("TITLE:"):
            title = line.replace("TITLE:", "").strip()
            continue

        if line.startswith("BODY:"):
            in_body = True
            continue

        if in_body:
            body_lines.append(line)

    body = "\n".join(body_lines).strip()

    return title, body


def build_fallback_body(diff: str, issue_number: str | None):
    body = f"""## Summary
        Automated changes generated by AI based on repository diff.
        
        ## Changes
        - Applied modifications based on issue requirements
        - Refer to diff for detailed changes
        
        ## Notes
        Diff truncated to 12k characters for processing.
        """

    if issue_number:
        body += f"\n---\nFixes #{issue_number}\n"

    return body


def main():
    diff = get_git_diff()
    issue_number = os.environ.get("ISSUE_NUMBER")

    ai = FallbackClient()

    user_prompt = f"""
        You are summarizing a git diff for a GitHub pull request.
        
        Analyze the diff and produce a concise PR title and a PR body.
        
        STRICT FORMAT:
        
        TITLE: <title>
        
        BODY:
        ## Summary
        Short explanation of what this PR does.
        
        ## Changes
        - bullet point describing key change
        - bullet point describing key change
        
        ## Related Issue
        Fixes #{issue_number}
        
        Git diff:
        {diff}
        """

    try:
        summary = ai.chat(
            system_prompt="Summarize git diffs into a concise PR title and description.",
            user_prompt=user_prompt,
        )
    except Exception as e:
        print(f"[WARN] LLM failed: {e}")
        summary = ""

    title, body = parse_summary(summary)

    # 🔥 Fallback if LLM output is broken or empty
    if not body.strip():
        print("[WARN] Empty or invalid LLM body, using fallback")
        body = build_fallback_body(diff, issue_number)

    # 🔒 Always enforce closing keyword (deterministic)
    if issue_number:
        if f"Fixes #{issue_number}" not in body:
            body = body.rstrip() + f"\n\n---\nFixes #{issue_number}\n"

    # 🧪 Debug (safe, useful)
    print("------ FINAL PR TITLE ------")
    print(title)
    print("------ FINAL PR BODY ------")
    print(body)
    print("----------------------------")

    github_env = os.environ["GITHUB_ENV"]

    with open(github_env, "a") as f:
        f.write(f"PR_TITLE={title}\n")
        f.write("PR_BODY<<EOF\n")
        f.write(body + "\n")
        f.write("EOF\n")


if __name__ == "__main__":
    main()
