"""Validate Codex's structured review and render a PR comment."""

from __future__ import annotations

import argparse
import json
from pathlib import Path, PurePosixPath
from typing import Any


def _validate(data: Any) -> dict[str, Any]:
    if not isinstance(data, dict):
        raise ValueError("review output must be a JSON object")
    if set(data) != {"verdict", "summary", "findings"}:
        raise ValueError("review output has unexpected or missing keys")

    verdict = data["verdict"]
    summary = data["summary"]
    findings = data["findings"]
    if verdict not in {"PASS", "FAIL"}:
        raise ValueError("verdict must be PASS or FAIL")
    if not isinstance(summary, str) or not summary.strip():
        raise ValueError("summary must be non-empty")
    if not isinstance(findings, list):
        raise ValueError("findings must be an array")
    if verdict == "PASS" and findings:
        raise ValueError("PASS cannot contain findings")
    if verdict == "FAIL" and not findings:
        raise ValueError(
            "Codex review did not complete: FAIL contained no actionable findings. "
            f"Reviewer summary: {summary.strip()}"
        )

    required = {"priority", "path", "line", "title", "body"}
    for index, finding in enumerate(findings, start=1):
        if not isinstance(finding, dict) or set(finding) != required:
            raise ValueError(f"finding {index} has invalid keys")
        if finding["priority"] not in {"P0", "P1", "P2"}:
            raise ValueError(f"finding {index} has invalid priority")
        if not isinstance(finding["line"], int) or finding["line"] < 1:
            raise ValueError(f"finding {index} has invalid line")
        path = PurePosixPath(str(finding["path"]))
        if path.is_absolute() or ".." in path.parts:
            raise ValueError(f"finding {index} has unsafe path")
        for field in ("path", "title", "body"):
            if not isinstance(finding[field], str) or not finding[field].strip():
                raise ValueError(f"finding {index} has empty {field}")
    return data


def _render(data: dict[str, Any]) -> str:
    verdict = data["verdict"]
    icon = "✅" if verdict == "PASS" else "❌"
    lines = [
        "## Codex production-safety review",
        "",
        f"{icon} **Verdict: {verdict}**",
        "",
        data["summary"].strip(),
    ]
    for finding in data["findings"]:
        lines.extend(
            [
                "",
                f"### [{finding['priority']}] {finding['title'].strip()}",
                "",
                f"`{finding['path']}:{finding['line']}`",
                "",
                finding["body"].strip(),
            ]
        )
    lines.extend(
        [
            "",
            "_Generated by Codex in an ephemeral read-only GitHub Actions job._",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    data = _validate(json.loads(args.input.read_text(encoding="utf-8")))
    args.output.write_text(_render(data), encoding="utf-8")
    print(f"verdict={data['verdict']}")
    print(f"findings={len(data['findings'])}")


if __name__ == "__main__":
    main()
