version: 1

formatters:
  colored:
    class: colorlog.ColoredFormatter
    format: "%(log_color)s%(filename)s | %(levelname)s | %(message)s"
    log_colors:
      DEBUG:    cyan
      INFO:     green
      WARNING:  yellow
      ERROR:    red
      CRITICAL: bold_red

  detailed:
    format: "%(filename)s | %(levelname)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: colored
    stream: ext://sys.stdout

  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: detailed
    filename: app.log
    encoding: utf8

loggers:
  Orbit:
    level: DEBUG
    handlers: [console, file]
    propagate: no

root:
  level: INFO
  handlers: [console]
