strategies:
  BCHUSDT:
    strategy: orbit.strategies.reversal_strategy.BollingerAdaptiveReversalStrategyBCH

  ETHUSDT:
    strategy: orbit.strategies.eth_strategy.ETHStrategy

  BTCUSDT:
    strategy: orbit.strategies.swing_strategy.SwingStrategyBTC
