WEBHOOKS = {
    "logs": "",
    "params": "",
    "active_trades": "",
    "signal": "",
    "exception": "",
    "exception_params": "",
    "cooldown": "",
    "sl_update": "",
    "true_alarm": "",
    "false_alarm": "",
    "active_trade_prices": "",
    "ai_predictions": "",
    "average_alarm": "",
    "market_sentiment": "",
    "alerts": "",
    "websocket": "",
    "chart_signal": "",
    "levels_webhook": "",
}
