name: Update Supermemory

on:
  push:  # because if condition is required for PR merge
    branches:
      - main
jobs:
  update-memory:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install deps
        run: |
          pip install supermemory openai

      - name: Update supermemory
        run: python .github/scripts/update_supermemory.py
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.merge_commit_sha }}
          SUPERMEMORY_API_KEY: ${{ secrets.SUPERMEMORY_API_KEY }}
          MODEL_TOKEN: ${{ secrets.MODEL_TOKEN }}
